spring:
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        period: 0
        cachecontrol:
          no-cache: true
          no-store: true
          must-revalidate: true
  devtools:
    restart:
      enabled: true
      additional-paths:
        - src/main/resources/templates
        - src/main/resources/static
    livereload:
      enabled: true

server:
  servlet:
    session:
      persistent: false
